/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicRouteRouteImport } from './routes/$topic/route'
import { Route as TopicYearIndexRouteImport } from './routes/$topic/$year/index'
import { Route as TopicYearSessionIdIndexRouteImport } from './routes/$topic/$year/$sessionId/index'
import { Route as TopicYearSessionIdSettingsRouteImport } from './routes/$topic/$year/$sessionId/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicRouteRoute = TopicRouteRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicYearIndexRoute = TopicYearIndexRouteImport.update({
  id: '/$year/',
  path: '/$year/',
  getParentRoute: () => TopicRouteRoute,
} as any)
const TopicYearSessionIdIndexRoute = TopicYearSessionIdIndexRouteImport.update({
  id: '/$year/$sessionId/',
  path: '/$year/$sessionId/',
  getParentRoute: () => TopicRouteRoute,
} as any)
const TopicYearSessionIdSettingsRoute =
  TopicYearSessionIdSettingsRouteImport.update({
    id: '/$year/$sessionId/settings',
    path: '/$year/$sessionId/settings',
    getParentRoute: () => TopicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$topic': typeof TopicRouteRouteWithChildren
  '/$topic/$year/': typeof TopicYearIndexRoute
  '/$topic/$year/$sessionId/settings': typeof TopicYearSessionIdSettingsRoute
  '/$topic/$year/$sessionId/': typeof TopicYearSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$topic': typeof TopicRouteRouteWithChildren
  '/$topic/$year': typeof TopicYearIndexRoute
  '/$topic/$year/$sessionId/settings': typeof TopicYearSessionIdSettingsRoute
  '/$topic/$year/$sessionId': typeof TopicYearSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$topic': typeof TopicRouteRouteWithChildren
  '/$topic/$year/': typeof TopicYearIndexRoute
  '/$topic/$year/$sessionId/settings': typeof TopicYearSessionIdSettingsRoute
  '/$topic/$year/$sessionId/': typeof TopicYearSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$topic'
    | '/$topic/$year/'
    | '/$topic/$year/$sessionId/settings'
    | '/$topic/$year/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$topic'
    | '/$topic/$year'
    | '/$topic/$year/$sessionId/settings'
    | '/$topic/$year/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/$topic'
    | '/$topic/$year/'
    | '/$topic/$year/$sessionId/settings'
    | '/$topic/$year/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TopicRouteRoute: typeof TopicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$topic': {
      id: '/$topic'
      path: '/$topic'
      fullPath: '/$topic'
      preLoaderRoute: typeof TopicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$topic/$year/': {
      id: '/$topic/$year/'
      path: '/$year'
      fullPath: '/$topic/$year/'
      preLoaderRoute: typeof TopicYearIndexRouteImport
      parentRoute: typeof TopicRouteRoute
    }
    '/$topic/$year/$sessionId/': {
      id: '/$topic/$year/$sessionId/'
      path: '/$year/$sessionId'
      fullPath: '/$topic/$year/$sessionId/'
      preLoaderRoute: typeof TopicYearSessionIdIndexRouteImport
      parentRoute: typeof TopicRouteRoute
    }
    '/$topic/$year/$sessionId/settings': {
      id: '/$topic/$year/$sessionId/settings'
      path: '/$year/$sessionId/settings'
      fullPath: '/$topic/$year/$sessionId/settings'
      preLoaderRoute: typeof TopicYearSessionIdSettingsRouteImport
      parentRoute: typeof TopicRouteRoute
    }
  }
}

interface TopicRouteRouteChildren {
  TopicYearIndexRoute: typeof TopicYearIndexRoute
  TopicYearSessionIdSettingsRoute: typeof TopicYearSessionIdSettingsRoute
  TopicYearSessionIdIndexRoute: typeof TopicYearSessionIdIndexRoute
}

const TopicRouteRouteChildren: TopicRouteRouteChildren = {
  TopicYearIndexRoute: TopicYearIndexRoute,
  TopicYearSessionIdSettingsRoute: TopicYearSessionIdSettingsRoute,
  TopicYearSessionIdIndexRoute: TopicYearSessionIdIndexRoute,
}

const TopicRouteRouteWithChildren = TopicRouteRoute._addFileChildren(
  TopicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TopicRouteRoute: TopicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
